services:
  php:
    image: docker_test-php:latest
    container_name: php_server
    ports:
      - "8080:80"
    volumes:
      - /g/S5/ConcObj-Tahina/etudiant:/var/www/html
    depends_on:
      - db
    command: php -S 0.0.0.0:80 -t /var/www/html

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_scolarite
    ports:
      - "3306:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
